title: Froxlor Documentation
remote_theme: pmarsceill/just-the-docs

# Search
search_enabled: true

# Plugins
plugins:
  - jekyll-remote-theme

# Disable the feed
feed:
  disable: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/img/logo.png"
color_scheme: froxlor

# Aux links for the upper right navigation
aux_links:
  "Froxlor on GitHub":
    - "https://github.com/Froxlor/Froxlor"
  "Join us on Discord":
    - "https://discord.froxlor.org/"

# Footer content
footer_content: "Copyright &copy; 2022 Froxlor Team."

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Froxlor/Documentation"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

# Collections (for the navigation)
collections:
  general:
        output: true
  adminguide:
        output: true
  userguide:
        output: true
  special:
        output: true

just_the_docs:
  collections:
    general:
      name: General
    adminguide:
      name: Admin Guide
    userguide:
      name: User Guide
    special:
      name: Special
