name: build-docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Build configs
        run: php generate.php
        working-directory: .generator
      - name: Commit changes
        run: |
          git config --global user.name 'envoyr'
          git config --global user.email 'hello@envoyr.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout "${GITHUB_REF:11}"
          git add -A
          git commit -am "publish new api documentation [automated]"
          git push
        working-directory: .